import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { getSession, signIn, signOut, useSession } from "next-auth/react"
import type { NextPage, NextPageContext } from "next"
import Auth from "../components/Auth"
import Application from '../components/Application'

import { useState } from 'react'
import { useMutation } from '@apollo/client'
import BookOpperations from '../graphql/operations/books'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  //session data
  const { data: session } = useSession();
  console.log("here is data", session)

  const reloadSession = () => {};


  //to be DELETED*************************************************************************************************************************
  const [ bookToBeAdded, setBookToBeAdded ] = useState('')

  const [ createBookAdded, {data, loading, error} ] = useMutation(BookOpperations.Mutations.CREATE_BOOK)

  console.log('HERE IS DATA', data, loading, error)

  const onSubmit = async () => {
    try {
      await createBookAdded( {variables: {title: bookToBeAdded}} )
    } catch(error) {
      console.log("onsubmit error", error)
    }
  }


  //above is to be DELETED******************************************************************************************************************

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by signing in&nbsp;
            <code className={styles.code}>look below</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
        {session?.user ? (
          <>
            <button onClick={() => signOut()}>Sign Out</button>
            <h6>{session?.user?.name}</h6>
            <input 
                    placeholder="enter a book" 
                    value={bookToBeAdded} 
                    onChange={(event) => setBookToBeAdded(event.target.value)}/>
                <button onClick={onSubmit}>Save</button>
            <input />
          </>
         ) : (
            <button onClick={() => signIn('google')}>Sign In</button>
         )
        }
        <div>{session?.user ? <Application/> : <Auth session={session} reloadSession={reloadSession}/>}</div>
        <div>

        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context)

  return {
    props: {
      session
    }
  }

}
